### ISSUE TITLE
Misleading return in halDS2482_CountDevices()

### ISSUE THREAD

**Issue by spachner** [ksstech/onewire#1]
Hi,

congrats for your nice driver! 

I looks through the code and found something in halDS2482_CountDevices(). The docu says halDS2482_CountDevices() returns number of devices found. But coded is also in case of error erFAILURE is returned. This is misleading. I suggest a call-by-reference argument for number of devices found.

regards

spachner

**Comment by spachner** [comment]
Hi,

I do not know the coding  erSUCCESS and erFAILURE, unfortunaltey there is not header for them.
But I think I got your logic now:
halDS2482_CountDevices() return "normal" (for a successful run) integer values as number of found devices (0, 1, ...) but "special" integers as error. This does only work when the value range for successful runs never come in the range of the error code. 

I do not recommend functions returning business logic return values and error codes in same return return value.

I would recommend something like this this `bool halDS2482_CountDevices(uint32_t* pCount)` or if you really not more error codes than a simple `false` use `uint32_t halDS2482_CountDevices(uint32_t* pCount)`

regards

spachner

**Comment by ammaree** [comment]
Thanks for the feedback, appreciated.

The coding for erSUCCESS is 0 and erFAILURE is -1 hence they do not conflict with the maximum number of devices expected on a channel. Any positive value larger than 0 (1 -> 8) would indicate that one or more devices were found on the 1Wire bus/channel.

The decision to code the function this way was done to minimize stack requirements without compromising on the clarity of the values returned.

I am currently travelling and will be returning to SA in a week. I will have a look at your suggestion and revert.

**Comment by ammaree** [comment]
Sorry, forgot to mention that in our use case we have maximum 1 device on any channel at any time, hence the mention of 8 as maximum above.

The driver does however cater for different use cases where multiple devices could be present on the same channel/bus. The driver has not yet been tested in this use case so there could very well be some bugs lurking. The driver has also not been tested with devices other than the DS1990 iButtons.

**Comment by ammaree** [comment]
Think we can close this issue. The driver has evolved significantly and now handle a range of I2C bridges (any combination of DS248x's) as well as DS1820/DS18S20/DS18X20 thermometers.
